server:
  port: 1112

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  
  application:
    name: customerservice
    
#Discovery Server Access
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
      
